
development:
  adapter: postgresql
  encoding: unicode
  database: sensorLink_development
  pool: 5
  username: postgres
  password: <%= ENV['SENSORLINK_DATABASE_PASSWORD'] %>
  host: localhost
  port: 5432

test:
  adapter: postgresql
  encoding: unicode
  database: sensorLink_test
  pool: 5
  username: postgres
  password: <%= ENV['SENSORLINK_DATABASE_PASSWORD'] %>
  host: localhost
  port: 5432

production:
  adapter: postgresql
  encoding: unicode
  database: sensorLink_production
  username: postgres
  password: <%= ENV['SENSORLINK_DATABASE_PASSWORD'] %>
