# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 5a8fb26a4946e1e03b4997ee7a6789797b9920d88d9147e264f0dbabdbba585448c60cb57e7f843384c6bf9b416b688478b4c39fa25b8a07772785518b2b410a

test:
  secret_key_base: 7a039deaf0f41e0c50f5b986c384eb09d9384e4d917544a645603adde11bd329a879ce389c6ffc3b5721ea0baa30ebee73c69e4377880843e90c14052a358754

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
